export const MY_SAVED_WORKOUTS_URL = "/my-saved-workouts"
export const LOGIN_URL = "/login"
export const FEED_URL = "/"
export const CREATE_USER_URL = "/createUser"
export const CREATE_WORKOUT_URL = "/createWorkout"
